### ISSUE TITLE
Use vite, edit tabs design tokens, type rounded has no change

### ISSUE THREAD

**Issue by lyanmm** [arco-design/arco-design-vue#1138]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.27.0
- **Framework version:** Vue 3.2.33
- **Browser:** chrome101.0.4951.67
- **Reproduction Link:** https://stackblitz.com/edit/vitejs-vite-jesoo8?file=src%2FApp.vue&terminal=dev

## What is expected?
show correct tokens style

## Steps to reproduce
1.edit vite.config.js css options
2.use tabs component, set rounded type

## Extra info
please check other component

**Comment by flsion** [comment]
![image](https://user-images.githubusercontent.com/29793175/168997536-ab78ade8-addd-4a30-be37-1f8642c0c5e7.png)

@lyanmm  The token name does not need to contain "@"

**Comment by flsion** [comment]
You can refer to https://arco.design/vue/en-US/docs/theme#Less-variable-substitution . Confirm whether the style file in less format is imported into the project. 
`unplugin-vue-components` config: https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/arco.ts#L148

This issue is temporarily closed, if you still have questions, you can create a new one
