### ISSUE TITLE
add video preview

### ISSUE THREAD

**Issue by francisxihe** [arco-design/arco-design-vue#3069]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
similar to image preview，preserve a sense of unity of style

## What problem does this feature solve?
Easy video preview

**Comment by LIjiAngChen8** [comment]
视频组件比较大内容多维护工作量大，暂时是没有这个组件计划，你可以试试 https://github.com/bytedance/xgplayer 

The video component is quite hefty and requires a significant amount of upkeep due to its extensive content. At the moment, we don't have any plans to develop this component. However, you might want to give https://github.com/bytedance/xgplayer a shot—it's worth a try!
